ASMWebTest1Project/Models/Ideas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebTest1Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ideas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ideas()
        {
            this.Interactive = new HashSet<Interactive>();
            this.LikeDislike = new HashSet<LikeDislike>();
            this.Replies = new HashSet<Replies>();
        }
    
        public int ideaID { get; set; }
        public string ideaTitle { get; set; }
        public System.DateTime creatAt { get; set; }
        public byte[] fileI { get; set; }
        public string urlFile { get; set; }
        public string description { get; set; }
        public Nullable<int> categoryID { get; set; }
        public int likes { get; set; }
        public int dislikes { get; set; }
        public string Iname { get; set; }
        public string incognito { get; set; }
        public int CountViews { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interactive> Interactive { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeDislike> LikeDislike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Replies> Replies { get; set; }
    }
}

ASMWebTest1Project/Controllers/IdeasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using ASMWebTest1Project.Models;
using Ionic.Zip;
using PagedList;

namespace ASMWebTest1Project.Controllers
{
    [Authorize]
    public class IdeasController : Controller
    {
        private ASMWebTest1Entities db = new ASMWebTest1Entities();

        // GET: Ideas
        public ActionResult IndexGuest(string Sorting_Order, string Search_Data, string Filter_Value, int? Page_No)
        {
            ViewBag.CurrentSortOrder = Sorting_Order;
            ViewBag.SortingTitle= String.IsNullOrEmpty(Sorting_Order) ? "Title_Idea" : "";
            ViewBag.SortingCreateOn = String.IsNullOrEmpty(Sorting_Order) ? "CreateOn" : "CreateOn_Desc";
            ViewBag.SortingCategory = String.IsNullOrEmpty(Sorting_Order) ? "Category_Name" : "Category_Name_Desc";

            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }
            ViewBag.FilterValue = Search_Data;

            var idea = from ide in db.Ideas select ide;
            if (!String.IsNullOrEmpty(Search_Data))
            {
                idea = idea.Where(ide => ide.ideaTitle.ToUpper().Contains(Search_Data.ToUpper()));
            }
            switch (Sorting_Order)
            {
                case "Title_Idea":
                    idea = idea.OrderByDescending(ide => ide.ideaTitle);
                    break;
                case "CreateOn":
                    idea = idea.OrderBy(ide => ide.creatAt);
                    break;
                case "CreateOn_Desc":
                    idea = idea.OrderByDescending(ide => ide.creatAt);
                    break;
                case "Category_Name":
                    idea = idea.OrderBy(ide => ide.Categories.categoryName);
                    break;
                case "Category_Name_Desc":
                    idea = idea.OrderByDescending(ide => ide.Iname);
                    break;
                default:
                    idea = idea.OrderBy(ide => ide.Categories.categoryName);
                    break;
            }
            int Size_Of_Page = 5;
            int No_Of_Page = (Page_No ?? 1);
            return View(idea.Where(i => i.Iname == User.Identity.Name).ToPagedList(No_Of_Page, Size_Of_Page));


        }
        /*public ActionResult IndexGuest()
        {
            var ideas = db.Ideas.Include(i => i.Categories);
            return View(ideas.ToList());
        }*/
        public ActionResult TestIndex(string Sorting_Order, string Search_Data, string Filter_Value, int? Page_No)
        {
            var mostPopular = from a in db.view_d select a;
            //GET MOST VIEW IDEA
            var mostViewed = from b in db.view_e select b;
            ViewBag.MostPopular = mostPopular;
            ViewBag.MostViewed = mostViewed;
            int countIdeas = (from c in db.Ideas select c).Count();

            ViewBag.countIdea = countIdeas;
            ViewBag.CurrentSortOrder = Sorting_Order;
            ViewBag.SortingTitle = String.IsNullOrEmpty(Sorting_Order) ? "Title_Idea" : "";
            ViewBag.SortingCreateOn = String.IsNullOrEmpty(Sorting_Order) ? "CreateOn" : "CreateOn_Desc";
            ViewBag.SortingCategory = String.IsNullOrEmpty(Sorting_Order) ? "Category_Name" : "Category_Name_Desc";

            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }
            ViewBag.FilterValue = Search_Data;

            var idea = from ide in db.Ideas select ide;
            if (!String.IsNullOrEmpty(Search_Data))
            {
                idea = idea.Where(ide => ide.ideaTitle.ToUpper().Contains(Search_Data.ToUpper()));
            }
            switch (Sorting_Order)
            {
                case "Title_Idea":
                    idea = idea.OrderByDescending(ide => ide.ideaTitle);
                    break;
                case "CreateOn":
                    idea = idea.OrderBy(ide => ide.creatAt);
                    break;
                case "CreateOn_Desc":
                    idea = idea.OrderByDescending(ide => ide.creatAt);
                    break;
                case "Category_Name":
                    idea = idea.OrderBy(ide => ide.Categories.categoryName);
                    break;
                case "Category_Name_Desc":
                    idea = idea.OrderByDescending(ide => ide.Iname);
                    break;
                default:
                    idea = idea.OrderBy(ide => ide.Categories.categoryName);
                    break;
            }
            int Size_Of_Page = 5;
            int No_Of_Page = (Page_No ?? 1);
            return View(idea.ToPagedList(No_Of_Page, Size_Of_Page));

        }
        // GET: Ideas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ideas ideas = db.Ideas.Find(id);
            if (DateTime.Now > db.Categories.Find(ideas.categoryID).finalDate)
            {

                return View("~/Views/Shared/_MainMenu.cshtml");

            }
            if (ideas == null)
            {
                return HttpNotFound();
            }
            Ideas update = db.Ideas.ToList().Find(u => u.ideaID == id);
            update.CountViews += 1;
            db.SaveChanges();
            return View(ideas);
        }
        public ActionResult Views(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            } 
            Ideas ideas = db.Ideas.Find(id);
            if (ideas == null)
            {
                return HttpNotFound();
            }
            Ideas update = db.Ideas.ToList().Find(u => u.ideaID == id);
            update.CountViews += 1;
            db.SaveChanges();
            return View(ideas);
        }

        // GET: Ideas/Create
        public ActionResult Create()
        {
            ViewBag.categoryID = new SelectList(db.Categories, "categoryID", "categoryName");
            
            return View();
        }
        
        // POST: Ideas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ideaID,ideaTitle,creatAt,fileI,urlFile,description,likes,dislikes,categoryID,Iname, incognito,CountViews")] Ideas ideas, HttpPostedFileBase file)
        {
            
            bool notifi = true;
          
            if (file != null && file.ContentLength > 0)
            {
                ideas.fileI = new byte[file.ContentLength]; // image stored in binary formate
                file.InputStream.Read(ideas.fileI, 0, file.ContentLength);
                string fileName = System.IO.Path.GetFileName(file.FileName);
                string UrlFile = Server.MapPath("~/FileI/" + fileName);
                file.SaveAs(UrlFile);

                ideas.urlFile = "FileI/" + fileName;
            }
            if(ideas.creatAt > db.Categories.Find(ideas.categoryID).closureDate)
            {
                notifi = false;

            }
            if (ModelState.IsValid)
            {
                if (notifi)
                {
                    var user = db.Information.FirstOrDefault(x => x.Irole == "Quality Assurance Coordinator").email;
                    string subject = "Notifaction";
                    int? ids = db.Ideas.Max(item => (int?)item.ideaID + 1);
                    
                    string body = ideas.Iname + " just sent the idea. Link:" + "https://localhost:44345/Ideas/Details/" + ids;
                    MailMessage mm = new MailMessage();
                    mm.To.Add(new MailAddress(user));
                    mm.Subject = subject;
                    mm.Body = body;
                    mm.From = new MailAddress("visualnotifaction@gmail.com");
                    mm.IsBodyHtml = false;
                    SmtpClient smtp = new SmtpClient("smtp.gmail.com");
                    smtp.Port = 587;
                    smtp.UseDefaultCredentials = true;
                    smtp.EnableSsl = true;
                    smtp.Credentials = new System.Net.NetworkCredential("visualnotifaction@gmail.com", "1900100Co");
                    smtp.Send(mm);
                    db.Ideas.Add(ideas);
                    db.SaveChanges();
                    return RedirectToAction("IndexGuest");
                }
                else
                {
                    ViewBag.message = "Create is fail, compose is close!";
                }
            }

            ViewBag.categoryID = new SelectList(db.Categories, "categoryID", "categoryName",ideas.categoryID);


            return View(ideas);
        }

        public ActionResult Download(string fileName)
        {
                string fullPath = Path.Combine(Server.MapPath("~/"), fileName);
            byte[] fileBytes = System.IO.File.ReadAllBytes(fullPath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public ActionResult DownloadAll()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/FileI/"));
            List<FileModel> files = new List<FileModel>();
            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel()
                {
                    FileName = Path.GetFileName(filePath),

ASMWebTest1Project/Views/Ideas/Create.cshtml
@model ASMWebTest1Project.Models.Ideas

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<style>
    .container {
        
        margin: 0 auto;
    }
</style>
<section class="home-section">
    <nav>
        <div class="sidebar-button">

            <span class="dashboard">6Bros</span>
        </div>
        <div class="search-box" style="display: flex">
            @using (Html.BeginForm("Index", "Ideas", FormMethod.Get))
            {
                @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @placeholder = "Search" })
                <input class="search" type="submit" value="     " /><i class="fa fa-search" style="font-size: 28px; position: absolute;left: 270px;top: 10px;"></i>
            }
        </div>
        <div class="profile-details">

            <span class="admin_name">
                Welcome, @Html.DisplayFor(modelItem => User.Identity.Name)
            </span>

        </div>
    </nav>
    /////////////////////////
    <div class="home-content">


        <div class="sales-boxes">
            <div class="recent-sales box">
                <div class="sales-details" style="display:block">
                    @using (Html.BeginForm("Create",
                         "Ideas",
                         FormMethod.Post,
                         new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                    <div class="container" id="ctn">
                        <h3 class="text-center">Submit Idea</h3>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <h4>Title Idea</h4>
                            <div>
                                @Html.EditorFor(model => model.ideaTitle, new { htmlAttributes = new { @class = "form-control " } })
                                @Html.ValidationMessageFor(model => model.ideaTitle, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @Html.Hidden("creatAt", DateTime.Now)



                        <div class="form-group">
                            <h4>File</h4>
                            <div>
                                <input type="file" name="file" />
                                @Html.ValidationMessageFor(model => model.fileI, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @Html.Hidden("Iname", User.Identity.Name)
                        <div class="form-group">
                            <h4>Description</h4>
                            <div>
                                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control text-center" } })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <h4>Compose</h4>
                            <div id="mySelect">
                                @Html.DropDownList("categoryID", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.categoryID, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="form-group">
                            
                            <div>
                                <h4>Anonymous @Html.CheckBox("incognito", false)</h4>
                                
                            </div>
                        </div>
                        <div style="color:red;margin:10px" class="text-center">
                            @ViewBag.message
                        </div>

                        <div class="form-group">
                            <div class="text-center">
                                <button type="submit" class="btn btn-success" onclick="return confirm('      Are you understand about Term and Policy?        Abusive users — Terms and conditions allow you to establish what constitutes appropriate activity on your site or app, so you can remove abusive users and content that violates your guidelines.Intellectual property theft — Asserting your claim to the creative assets of your site in your terms and conditions will prevent ownership disputes and copyright infringement.Potential litigation — If a user lodges a legal complaint against your business, showing that they were presented with clear terms and conditions before they used your site will help you immensely in court.')">Submit</button>
                            </div>
                        </div>
                    </div>
                        
                    }
                </div>
            </div>

        </div>


    </div>

    
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</section>







  

ASMWebTest1Project/Views/Ideas/Delete.cshtml
@model ASMWebTest1Project.Models.Ideas

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<section class="home-section">
    <nav>
        <div class="sidebar-button">

            <span class="dashboard">6Bros</span>
        </div>
        <div class="search-box" style="display: flex">
            @using (Html.BeginForm("Index", "Ideas", FormMethod.Get))
            {
                @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @placeholder = "Search" })
                <input class="search" type="submit" value="     " /><i class="fa fa-search" style="font-size: 28px; position: absolute;left: 270px;top: 10px;"></i>
            }
        </div>
        <div class="profile-details">

            <span class="admin_name">
                Welcome, @Html.DisplayFor(modelItem => User.Identity.Name)
            </span>

        </div>
    </nav>
    /////////////////////////
    <div class="home-content">


        <div class="sales-boxes">
            <div class="recent-sales box">
                <div class="sales-details" style="display:block">
                    <div class="container" id="ctn">
                        <h3 class="text-center" >Ideas</h3>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.ideaTitle)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ideaTitle)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.creatAt)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.creatAt)
                            </dd>



                            <dt style="display:none">
                                @Html.DisplayNameFor(model => model.fileI)
                            </dt>

                            <dd style="display:none">
                                @Html.DisplayFor(model => model.fileI)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.urlFile)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.urlFile)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.description)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.description)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Categories.categoryName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Categories.categoryName)
                            </dd>



                        </dl>


                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure to delete?')" /> |
                            @Html.ActionLink("Back to List", "IndexGuest")
                        </div>
                    }
                </div>
            </div>

        </div>


    </div>


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</section>

ASMWebTest1Project/Views/Ideas/DownloadAll.cshtml
@using ASMWebTest1Project.Models
@model List<FileModel>
@{
    ViewBag.Title = "DownloadAll";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<section class="home-section">
    <nav>
        <div class="sidebar-button">

            <span class="dashboard">6Bros</span>
        </div>
        <div class="search-box" style="display: flex">
            @using (Html.BeginForm("Index", "Ideas", FormMethod.Get))
            {
                @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @placeholder = "Search" })
                <input class="search" type="submit" value="     " /><i class="fa fa-search" style="font-size: 28px; position: absolute;left: 270px;top: 10px;"></i>
            }
        </div>
        <div class="profile-details">

            <span class="admin_name">
                Welcome, @Html.DisplayFor(modelItem => User.Identity.Name)
            </span>

        </div>
    </nav>
    /////////////////////////
    <div class="home-content">


        <div class="sales-boxes">
            <div class="recent-sales box">
                <div class="sales-details" style="display:block">
                    @using (Html.BeginForm("DownloadAll", "Ideas", FormMethod.Post))
                    {
                        <table class="table table-bordered table-condensed">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" onclick="toggle(this);" /> Select all<br /></th>
                                    <th>File Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < Model.Count(); i++)
                                {
                                    <tr>
                                        <td>@Html.CheckBoxFor(model => model[i].IsSelected)</td>
                                        <td>
                                            @Model[i].FileName
                                            @Html.HiddenFor(model => model[i].FilePath)
                                            @Html.HiddenFor(model => model[i].FileName)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <br />
                        
                        <input type="submit" style="        padding: 5px 10px;
        border-radius: 5px;
        border: none;
        background-color: rgb(39, 118, 180);
        color: white;" value="Download All" />
        <label style="font-size: 12px; font-weight: normal">*Download all file as Zip</label>

    <script>
        function toggle(source) {
            var checkboxes = document.querySelectorAll('input[type="checkbox"]');
            for (var i = 0; i < checkboxes.length; i++) {
                if (checkboxes[i] != source)
                    checkboxes[i].checked = source.checked;
            }
        }
    </script>
    }
</div>
            </div>

        </div>


    </div>


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</section>

ASMWebTest1Project/Views/Ideas/Edit.cshtml
@model ASMWebTest1Project.Models.Ideas

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<section class="home-section">
    <nav>
        <div class="sidebar-button">

            <span class="dashboard">Dashboard</span>
        </div>
        <div class="search-box" style="display: flex">
            @using (Html.BeginForm("Index", "Ideas", FormMethod.Get))
            {
                @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @placeholder = "Search" })
                <input class="search" type="submit" value="     " /><i class="fa fa-search" style="font-size: 28px; position: absolute;left: 275px;top: 10px;"></i>
            }
        </div>
        <div class="profile-details">

            <span class="admin_name">
                Welcome, @Html.DisplayFor(modelItem => User.Identity.Name)
            </span>

        </div>
    </nav>

    <div class="home-content">


        <div class="sales-boxes">
            <div class="recent-sales box">
                <div class="sales-details" style="display:block">
                    @using (Html.BeginForm("Edit", "Ideas", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                    <div class="container" id="ctn">
                        <h3 class="text-center">Edit Ideas</h3>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ideaID)

                        <div class="form-group">
                            <h4>Title Ideas</h4>
                            <div>
                                @Html.EditorFor(model => model.ideaTitle, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ideaTitle, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <h4>File</h4>
                            <div>
                                <input type="file" name="editFile" id="editFile" style="width: 100%;" />
                            </div>
                        </div>
                        <div class="form-group">
                            <h4>Description</h4>
                            <div>
                                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @Html.HiddenFor(model => model.categoryID)

                        @Html.Hidden("Iname", User.Identity.Name)
                        @ViewBag.message
                        <div class="form-group">
                            <div class="text-center">
                                <input type="submit" value="Save" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                    }
                    
                </div>
            </div>

        </div>


    </div>


    

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</section>

ASMWebTest1Project/Views/Ideas/Index.cshtml
@model IEnumerable<ASMWebTest1Project.Models.Ideas>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<button class="btn btn-primary">
    @Html.ActionLink("Create New", "Create")
</button>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ideaTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creatAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Iname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.urlFile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categories.categoryName)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ideaTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.creatAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Iname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.urlFile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categories.categoryName)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ideaID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ideaID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ideaID })
        </td>
    </tr>
}

</table>